### ISSUE TITLE
Catch hook issues

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot#188]
`ServerProvider.java:75` catch here and display the error (too), instead of having to open the console.

**Comment by JKetelaar** [comment]
```
java.lang.NullPointerException
    at org.parabot.core.asm.wrappers.Getter.<init>(Getter.java:44)
    at org.parabot.core.parsers.hooks.XMLHookParser.getGetters(XMLHookParser.java:189)
    at org.parabot.core.parsers.hooks.HookParser.getInjectables(HookParser.java:43)
    at org.parabot.environment.servers.ServerProvider.injectHooks(ServerProvider.java:75)
    at org.rev317.min.Loader.injectHooks(Loader.java:79)
    at org.parabot.core.Context.load(Context.java:172)
    at org.parabot.environment.servers.executers.ServerExecuter$1.run(ServerExecuter.java:25)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by AlexanderBielen** [comment]
http://prntscr.com/lnabm5
Like this, or display the actual stack trace?

```
int brokenHookCount = 0;

        for (Injectable inj : injectables) {
            try {
                inj.inject();
            } catch (NullPointerException ex) {
                if(Core.inVerboseMode()) {
                    System.err.print("Broken hook caught : ");
                    ex.printStackTrace();
                }
                brokenHookCount++;
            }
        }

        if(brokenHookCount > 0) {
            System.out.println("Number of broken hooks: " + brokenHookCount);
            UILog.log("Outdated hooks", "Looks like some hooks are outdated, report this on the forums in the 'Server providers -> Reports' section.");
}
```
This makes it so the client doesn't crash, not sure if you want it to because some scripts might not function.

**Comment by JKetelaar** [comment]
We should make the client crash though, it shouldn't just continue.
Displaying the error looks good!

But let the client crash **and** display the error would be better.

**Comment by PBLord** [comment]
Just a suggestion but how about wording it 

"This server currently has outdated hooks, Please report it to a member of the Parabot staff/Dev Team"
Or Something like "This client is outdated, Please click here for info" Then it will take them to thread with reports/updates?  Something like this?

**Comment by AlexanderBielen** [comment]
> We should make the client crash though, it shouldn't just continue.
> Displaying the error looks good!
> 
> But let the client crash **and** display the error would be better.

Crash on the first error and display only this one, or catch them all and crash and display all of them?

**Comment by JKetelaar** [comment]
Crash on the first one would be the best!
