### ISSUE TITLE
Unable to set network.

### ISSUE THREAD

**Issue by apalapa** [Parabot/Parabot#19]
Upon opening the network window and then clicking "ok" to any settings (default included, VPN or not). The client freezes with (the dropdown menus part of the window are still responsive): This is in IKOV, and I belive the error can be avoided by setting networking before loading the server. 

Setting mac address to: (MY MAC)
Closing Existing Connections...
java.io.IOException: Stream closed.
        at java.net.AbstractPlainSocketImpl.available(Unknown Source)
        at java.net.SocketInputStream.available(Unknown Source)
        at java.io.BufferedInputStream.available(Unknown Source)
        at com.ikovps.client.A.A.E.Ó00000(Unknown Source)
        at com.ikovps.client.A.A.B.õ00000(Unknown Source)
        at com.ikovps.client.A.A.B.Ô00000(Unknown Source)
        at com.ikovps.client.A.A.void.Ô00000(Unknown Source)
        at com.ikovps.client.Client.super(Unknown Source)
        at com.ikovps.client.OooO.run(Unknown Source)
        at com.ikovps.client.Client.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Closing socket. 1
Exception in thread "Thread-10" java.lang.NoSuchMethodError: org.parabot.core.as
m.redirect.ThreadRedirect.join(Ljava/lang/Thread;)V
        at com.ikovps.client.A.A.E.Ò00000(Unknown Source)
        at com.ikovps.client.A.A.B.Ò00000(Unknown Source)
        at com.ikovps.client.A.A.void.Ò00000(Unknown Source)
        at com.ikovps.client.A.A.return.ô00000(Unknown Source)
        at com.ikovps.client.A.A.B.Ô00000(Unknown Source)
        at com.ikovps.client.A.A.void.Ô00000(Unknown Source)
        at com.ikovps.client.Client.super(Unknown Source)
        at com.ikovps.client.OooO.run(Unknown Source)
        at com.ikovps.client.Client.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Problem, connection could not be made to world4.ikovps.com:43597 :

**Comment by JKetelaar** [comment]
I'll assign this task to @mdbell

**Comment by mdbell** [comment]
Fix was just sent off to @JKetelaar so it should be fixed soon, the new security system broke thread joining and it was killing the client.

**Comment by apalapa** [comment]
Awesome, thanks for addressing this.

**Comment by JKetelaar** [comment]
Fixed in latest version.
