### ISSUE TITLE
Error when loading new server

### ISSUE THREAD

**Issue by lordgmage** [Parabot/Parabot#198]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The Parabot version and the operating system you're using
- [ ] The behaviour you expect to see, and the actual behaviour
- [ ] Steps to reproduce the behaviour 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behaviour, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

### Description
When loading new server log on fine, nothing shows. OS-Unity

```
Exception in thread "Thread-8" java.lang.NoSuchMethodError: org.parabot.core.asm.redirect.ClassRedirect.desiredAssertionStatus(Ljava/lang/Class;)Z
	at net.osrsunity.c.b.<clinit>(Unknown Source)
	at net.osrsunity.Client.E(Unknown Source)
	at net.osrsunity.Client.b(Unknown Source)
	at net.osrsunity.ap.run(Unknown Source)
	at net.osrsunity.Client.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JKetelaar** [comment]
Is this fixed in the latest beta release @lordgmage?
