### ISSUE TITLE
ClassRedirect getResource NoSuchMethodError

### ISSUE THREAD

**Issue by AlexanderBielen** [Parabot/Parabot#288]
When trying to get the location of an fxml file to use with javafx, I get thrown an error because of the ClassRedirect intercepting the call to the class loader. However inside the ClassRedirect class the #getResource method does not exist so following error is thrown:

Stacktrace:
```
Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: org.parabot.core.asm.redirect.ClassRedirect.getResource(Ljava/lang/Class;Ljava/lang/String;)Ljava/net/URL;
        at org.parabot.atex.dreamscape.ainstancefighter.ui.Gui.start(Gui.java:27)
        at org.parabot.atex.dreamscape.ainstancefighter.ui.Gui$1.run(Gui.java:46)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
```

Code:
```
stage = primaryStage;
stage.setTitle("Configure script");
FXMLLoader loader = new FXMLLoader();

loader.setLocation(this.getClass().getResource("/fxml/gui.fxml")); // This is where it crashes (line 27)

Parent page = loader.load();
Scene scene = new Scene(page);

stage.setScene(scene);
stage.show();
```

File layout:
[https://prnt.sc/lkcomn](https://prnt.sc/lkcomn)

A possible workaround for the error is to change the line to:
`loader.setLocation(this.getClass().getClassLoader().getResource("/fxml/gui.fxml"));`
Because ClassRedirect has a #getClassLoader function, however in this case it will throw a SecurityException which is by design.

Recreate it by simply making a javafx window with fxml and compiling and run it in a script.

**Comment by JKetelaar** [comment]
Method `getResource(Ljava/lang/Class;Ljava/lang/String;)Ljava/net/URL` needs to be added to [ClassRedirect](https://github.com/Parabot/Parabot/blob/deb8dff6963dd5b99e9ede41daf288a451370d8d/src/main/java/org/parabot/core/asm/redirect/ClassRedirect.java).

**Comment by AlexanderBielen** [comment]
Not sure what security you want to put on it, but doing this:
```
public static URL getResource(Class<?> c, String path) {
        if(validStack() || validRequest(c)) {
            return c.getResource(path);
        }

        System.err.println(c.getName() + "#getResource(" + path + ") Blocked.");
        throw RedirectClassAdapter.createSecurityException();
}
```
would still not allow user created classes to use the function and still throw a SecurityException:
```
org.parabot.atex.oswar.afisher.ui.GuiApp_parabot#getResource(/fxml/gui.fxml) Blocked.
java.lang.SecurityException: Unsafe operation blocked. Op:getResource
	at org.parabot.core.asm.RedirectClassAdapter.createSecurityException(RedirectClassAdapter.java:62)
	at org.parabot.core.asm.redirect.ClassRedirect.getResource(ClassRedirect.java:68)
	at org.parabot.atex.oswar.afisher.ui.GuiApp_parabot.start(GuiApp_parabot.java:25)
	at org.parabot.atex.oswar.afisher.ui.GuiApp_parabot$1.run(GuiApp_parabot.java:45)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by JKetelaar** [comment]
That is indeed what I meant, now the operation gets blocked, so we are one step further.

The line in your code:
```
        if(validStack() || validRequest(c)) {
```
Should avoid the block, so we might have to debug where the problem is coming from, as this operation should be allowed (for scripts)
