### ISSUE TITLE
[BUG] ExceptionInInitializerError - Version with RC doesn't work correctly

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot#79]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.parabot.core.Core.<clinit>(Core.java:36)
	at org.parabot.Landing.main(Landing.java:35)
Caused by: java.lang.IllegalArgumentException: Invalid version format
	at org.parabot.environment.api.utils.Version.<init>(Version.java:16)
	at org.parabot.core.ProjectProperties.getProjectVersion(ProjectProperties.java:40)
	at org.parabot.core.Configuration.<clinit>(Configuration.java:28)
	... 2 more
```

**Comment by JKetelaar** [comment]
Solves as of PR #80
