### ISSUE TITLE
PBPreferences Unexpected token END OF FILE

### ISSUE THREAD

**Issue by Fryslan** [Parabot/Parabot#99]
When trying to save data in PBPreferences i get this error:

```
Unexpected token END OF FILE at position 0.
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
	at org.parabot.environment.api.utils.PBPreferences.addSetting(PBPreferences.java:116)
	at com.fryslan.pkhonor.PreferencesExample.onExecute(PreferencesExample.java:22)
	at org.parabot.environment.scripts.Script.run(Script.java:77)
	at java.lang.Thread.run(Thread.java:745)
```

I was using this code when i got the error:

```
package com.fryslan.pkhonor;

import org.parabot.environment.api.utils.PBPreferences;
import org.parabot.environment.scripts.Category;
import org.parabot.environment.scripts.Script;
import org.parabot.environment.scripts.ScriptManifest;

@ScriptManifest(author = "Fryslan", name = "PreferencesExample", category = Category.OTHER, version = 1.0, description = "", servers = "")
public class PreferencesExample extends Script {

    public static PBPreferences preferences;
    public static int foodId;

    @Override
    public boolean onExecute() {

        preferences = getPreferences();

        preferences.addSetting("Food id",386);
        foodId = Integer.parseInt(preferences.getSetting("Food id"));

        System.out.println(foodId);

        return true;
    }
}
```

**Comment by JKetelaar** [comment]
Thanks for the report.

**Comment by JKetelaar** [comment]
Moved to YouTrack

**Comment by JKetelaar** [comment]
Moved to YouTrack [here](http://track.parabot.org:8080/issue/CLIENT-1).
